### ISSUE TITLE
Possiblity of hiding the left bar

### ISSUE THREAD

**Issue by amalk1** [teijo/jquery-bracket#59]
Hi, Is it possible to hide the left bar which has +,- and de, and still the bracket be editable?

**Comment by denkomanceski** [comment]
+1

**Comment by teijo** [comment]
As a temporary solution suggested in #71, you could use CSS to hide it until a built-in way is implemented.

```css
div.jQBracket .tools {
  display: none;
}
```
